export const INDUSTRIES = [
  'Automotive',
  'Real Estate',
  'Fitness',
  'Restaurant',
  'Beauty/Salon',
  'Healthcare',
  'Legal',
  'Finance',
  'Education',
  'Technology',
  'E-commerce',
  'Construction',
  'Photography',
  'Travel',
  'Pet Care',
  'Cleaning Services',
  'Landscaping',
  'Dental',
  'Chiropractic',
  'HVAC',
  'Plumbing',
  'Electrical',
  'Roofing',
  'Insurance',
  'Accounting',
  'Marketing Agency',
  'Wedding/Events',
  'Food & Beverage',
  'Fashion',
  'Home Decor',
] as const;
